<a href="https://colab.research.google.com/github/ankit497775/ankit497775/blob/main/Breast_cancer_p1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier


from sklearn.metrics import confusion_matrix

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report , recall_score



In [ ]:
# 1. Load dataset

df = pd.read_csv("/content/Breast_cancer_dataset.csv")
df.head()


id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
# train_test_split
# Drop 'id' (not a feature) and 'Unnamed: 32' (contains NaNs) to resolve scaling warnings

X = df.drop(['diagnosis', 'id', 'Unnamed: 32'], axis=1)
y = df['diagnosis']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.2 , random_state = 42)

In [ ]:
# 3. feature scaling

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
# 4. classification models

models = {
    "Logistic Regression": LogisticRegression(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier()
}

In [ ]:
# 5. Model evaluation function

def evaluate_model(model, X_test, y_test):
  y_pred = model.predict(X_test)

  return {
      "accuracy": accuracy_score(y_test, y_pred),
      "confusion_matrix": confusion_matrix(y_test, y_pred),
      "classification_report": classification_report(y_test, y_pred),

      "recall": recall_score(y_test,y_pred, pos_label='M')

  }

In [ ]:
# 6. Train & compare models

results = {}
for name, model in models.items():
  model.fit(X_train, y_train)
  results[name] = evaluate_model(model, X_test, y_test)

In [ ]:
results["Logistic Regression"]["confusion_matrix"]

array([[70,  1],
       [ 2, 41]])

In [ ]:
results["Decision Tree"]["confusion_matrix"]

array([[67,  4],
       [ 3, 40]])

In [ ]:
results["Random Forest"]["confusion_matrix"]

array([[70,  1],
       [ 3, 40]])

In [ ]:
print("Logistic Regression:")
print(results["Logistic Regression"]["classification_report"])
print("\nDecision Tree:")
print(results["Decision Tree"]["classification_report"])
print("\nRandom Forest:")
print(results["Random Forest"]["classification_report"])

Logistic Regression:
              precision    recall  f1-score   support

           B       0.97      0.99      0.98        71
           M       0.98      0.95      0.96        43

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114


Decision Tree:
              precision    recall  f1-score   support

           B       0.96      0.94      0.95        71
           M       0.91      0.93      0.92        43

    accuracy                           0.94       114
   macro avg       0.93      0.94      0.93       114
weighted avg       0.94      0.94      0.94       114


Random Forest:
              precision    recall  f1-score   support

           B       0.96      0.99      0.97        71
           M       0.98      0.93      0.95        43

    accuracy                           0.96       114
   macro avg       0.97      0.96      0.96       114
weighted avg       0.

In [ ]:
print("Logistic Regression:")
print(results["Logistic Regression"]["accuracy"])
print("\nDecision Tree:")
print(results["Decision Tree"]["accuracy"])
print("\nRandom Forest:")
print(results["Random Forest"]["accuracy"])

Logistic Regression:
0.9736842105263158

Decision Tree:
0.9385964912280702

Random Forest:
0.9649122807017544


In [ ]:
print("Logistic Regression:")
print(results["Logistic Regression"]["recall"])
print("\nDecision Tree:")
print(results["Decision Tree"]["recall"])
print("\nRandom Forest:")
print(results["Random Forest"]["recall"])

Logistic Regression:
0.9534883720930233

Decision Tree:
0.9302325581395349

Random Forest:
0.9302325581395349
