<a href="https://colab.research.google.com/github/ankit497775/ankit497775/blob/main/project3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [46]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score , confusion_matrix , recall_score , precision_score , f1_score

from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC


In [47]:
df = pd.read_csv("/content/predictive_maintenance_dataset.csv")
df.head()


UDI Product ID Type  Air temperature [K]  Process temperature [K]  \
0    1     M14860    M                298.1                    308.6   
1    2     L47181    L                298.2                    308.7   
2    3     L47182    L                298.1                    308.5   
3    4     L47183    L                298.2                    308.6   
4    5     L47184    L                298.2                    308.7   

   Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Machine failure  TWF  \
0                    1551         42.8                0                0    0   
1                    1408         46.3                3                0    0   
2                    1498         49.4                5                0    0   
3                    1433         39.5                7                0    0   
4                    1408         40.0                9                0    0   

   HDF  PWF  OSF  RNF  
0    0    0    0    0  
1    0    0    0    0  
2    0    0    0    0  
3    0    0    0    0  
4    0    0    0    0

In [48]:
# Drop non-predictive columns and handle categorical encoding
X = df.drop(['Machine failure', 'Product ID', 'UDI', 'TWF', 'HDF', 'PWF', 'OSF', 'RNF'], axis=1)
X = pd.get_dummies(X, columns=['Type'], drop_first=True)
y = df["Machine failure"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [49]:
# Feature Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [51]:
model = SVC(kernel = 'rbf' , C=1)
model.fit(X_train , y_train)

SVC(C=1)

In [52]:
svm_pred = model.predict(X_test)

In [53]:
print(accuracy_score(y_test , svm_pred))

0.977


In [54]:
print(confusion_matrix(y_test , svm_pred))

[[1936    3]
 [  43   18]]


In [55]:
from sklearn.metrics import f1_score

recall = recall_score(y_test , svm_pred)
print("Recall", recall)
precision = precision_score(y_test , svm_pred)
print("\nPrecision" , precision)
f1 = f1_score(y_test , svm_pred)
print("\nF1 Score" , f1)

Recall 0.29508196721311475

Precision 0.8571428571428571

F1 Score 0.43902439024390244


In [57]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(class_weight = 'balanced' , n_estimators=100)
model.fit(X_train, y_train)



RandomForestClassifier(class_weight='balanced')

In [58]:
rf_pred = model.predict(X_test)


In [59]:
print(accuracy_score(y_test , rf_pred))

0.9795


In [60]:
print(confusion_matrix(y_test , rf_pred))

[[1931    8]
 [  33   28]]


In [61]:
recall = recall_score(y_test , rf_pred)
print("Recall", recall)
precision = precision_score(y_test , rf_pred)
print("\nPrecision" , precision)
f1 = f1_score(y_test , rf_pred)
print("\nF1 Score" , f1)

Recall 0.45901639344262296

Precision 0.7777777777777778

F1 Score 0.5773195876288659


In [63]:
l1_model = LogisticRegression(class_weight = 'balanced', penalty = 'l1' , solver = 'liblinear')
l1_model.fit(X_train , y_train)

LogisticRegression(class_weight='balanced', penalty='l1', solver='liblinear')

In [64]:
l1_model = model.predict(X_test)

In [65]:
print(accuracy_score(y_test , l1_model))

0.9795


In [66]:
print(confusion_matrix(y_test , l1_pred))

[[1939    0]
 [   2   59]]


In [67]:

recall = recall_score(y_test , l1_pred)
print("Recall", recall)
precision = precision_score(y_test , l1_pred)
print("\nPrecision" , precision)
f1 = f1_score(y_test , l1_pred)
print("\nF1 Score" , f1)

Recall 0.9672131147540983

Precision 1.0

F1 Score 0.9833333333333333


In [ ]:
#### Logistic Regression is best suited for this dataset by the means of confusion matrix..